/*
  Dalhalla IoT — JSON-configured HAL/DAL + Script Engine
  HAL = Hardware Abstraction Layer
  DAL = Device Abstraction Layer

  Provides IoT firmware building blocks for home automation and smart sensors.

  Copyright (C) 2025 Jannik Svensson

  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or 
  (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the 
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License 
  along with this program. If not, see <https://www.gnu.org/licenses/>.
*/

#pragma once

#define DALHAL_REACTIVE_FEATURE_NONE           0x00000000

#define DALHAL_REACTIVE_FEATURE_BEGIN          0x00000001
#define DALHAL_REACTIVE_FEATURE_CYCLE_COMPLETE 0x00000002
#define DALHAL_REACTIVE_FEATURE_UNUSED_1       0x00000004
#define DALHAL_REACTIVE_FEATURE_UNUSED_2       0x00000008
#define DALHAL_REACTIVE_FEATURE_UNUSED_3       0x00000010
#define DALHAL_REACTIVE_FEATURE_UNUSED_4       0x00000020
#define DALHAL_REACTIVE_FEATURE_UNUSED_5       0x00000040
#define DALHAL_REACTIVE_FEATURE_UNUSED_6       0x00000080

#define DALHAL_REACTIVE_FEATURE_VALUE_CHANGE   0x00000100
#define DALHAL_REACTIVE_FEATURE_STATE_CHANGE   0x00000200
#define DALHAL_REACTIVE_FEATURE_UNUSED_7       0x00000400
#define DALHAL_REACTIVE_FEATURE_UNUSED_8       0x00000800
#define DALHAL_REACTIVE_FEATURE_UNUSED_9       0x00001000
#define DALHAL_REACTIVE_FEATURE_UNUSED_10      0x00002000
#define DALHAL_REACTIVE_FEATURE_UNUSED_11      0x00004000
#define DALHAL_REACTIVE_FEATURE_UNUSED_12      0x00008000

/* when the read function have executed successfully */
#define DALHAL_REACTIVE_FEATURE_READ           0x00010000
/* when the write function have executed successfully */
#define DALHAL_REACTIVE_FEATURE_WRITE          0x00020000
/* when the exec function have executed successfully */
#define DALHAL_REACTIVE_FEATURE_EXEC           0x00040000
#define DALHAL_REACTIVE_FEATURE_UNUSED_13      0x00080000
/* when the bracket read function have executed successfully */
#define DALHAL_REACTIVE_FEATURE_BRACKET_READ   0x00100000
/* when the bracket write function have executed successfully */
#define DALHAL_REACTIVE_FEATURE_BRACKET_WRITE  0x00200000
#define DALHAL_REACTIVE_FEATURE_UNUSED_14      0x00400000
#define DALHAL_REACTIVE_FEATURE_UNUSED_15      0x00800000

// errors
#define DALHAL_REACTIVE_FEATURE_READ_ERROR     0x01000000
#define DALHAL_REACTIVE_FEATURE_WRITE_ERROR    0x02000000
#define DALHAL_REACTIVE_FEATURE_EXEC_ERROR     0x04000000
#define DALHAL_REACTIVE_FEATURE_TIMEOUT        0x08000000

#define DALHAL_REACTIVE_FEATURE_UNUSED_16      0x10000000
#define DALHAL_REACTIVE_FEATURE_UNUSED_17      0x20000000
#define DALHAL_REACTIVE_FEATURE_UNUSED_18      0x40000000

//enabler, this is used to keep the Reactive Feature enabled when using custom events
#define DALHAL_REACTIVE_FEATURE_CUSTOM         0x80000000

#define DALHAL_REACTIVE_FEATURE_RW ( DALHAL_REACTIVE_FEATURE_READ | DALHAL_REACTIVE_FEATURE_WRITE )

#define DALHAL_REACTIVE_FEATURE_ALL ( \
                                        DALHAL_REACTIVE_FEATURE_CUSTOM | \
                                        DALHAL_REACTIVE_FEATURE_BEGIN | \
                                        DALHAL_REACTIVE_FEATURE_CYCLE_COMPLETE | \
                                        DALHAL_REACTIVE_FEATURE_VALUE_CHANGE | \
                                        DALHAL_REACTIVE_FEATURE_STATE_CHANGE | \
                                        DALHAL_REACTIVE_FEATURE_READ | \
                                        DALHAL_REACTIVE_FEATURE_WRITE | \
                                        DALHAL_REACTIVE_FEATURE_EXEC | \
                                        DALHAL_REACTIVE_FEATURE_BRACKET_READ | \
                                        DALHAL_REACTIVE_FEATURE_BRACKET_WRITE | \
                                        DALHAL_REACTIVE_FEATURE_TIMEOUT | \
                                        DALHAL_REACTIVE_FEATURE_WRITE_ERROR | \
                                        DALHAL_REACTIVE_FEATURE_READ_ERROR | \
                                        DALHAL_REACTIVE_FEATURE_EXEC_ERROR \
                                    )

// easy copy/paste template
#define DALHAL_REACTIVE_CFG_ (DALHAL_REACTIVE_FEATURE_NONE)

//#define DALHAL_REACTIVE_DEVELOPMENT_MODE
#ifndef DALHAL_REACTIVE_DEVELOPMENT_MODE

// Actuators
#define DALHAL_REACTIVE_CFG_ACTUATOR              (DALHAL_REACTIVE_FEATURE_WRITE | DALHAL_REACTIVE_FEATURE_STATE_CHANGE | DALHAL_REACTIVE_FEATURE_CUSTOM) /* implemented */
#define DALHAL_REACTIVE_CFG_RELAY_LATCHING        (DALHAL_REACTIVE_FEATURE_WRITE | DALHAL_REACTIVE_FEATURE_STATE_CHANGE | DALHAL_REACTIVE_FEATURE_CUSTOM) /* implemented */
#define DALHAL_REACTIVE_CFG_PWM_SERVO             (DALHAL_REACTIVE_FEATURE_WRITE) /* implemented */
// API

// DataStorageServices
#define DALHAL_REACTIVE_CFG_THINGSPEAK            (DALHAL_REACTIVE_FEATURE_EXEC) /* implemented, also as a consumer */
// DeviceContainer
#define DALHAL_REACTIVE_CFG_CONTAINER             (DALHAL_REACTIVE_FEATURE_NONE) /* nothing to implement */
// Display

// General Inputs
#define DALHAL_REACTIVE_CFG_ANALOG_INPUT          (DALHAL_REACTIVE_FEATURE_VALUE_CHANGE | DALHAL_REACTIVE_FEATURE_READ) /* implemented */
#define DALHAL_REACTIVE_CFG_BUTTON_INPUT          (DALHAL_REACTIVE_FEATURE_STATE_CHANGE | DALHAL_REACTIVE_FEATURE_CUSTOM) /* implemented */
#define DALHAL_REACTIVE_CFG_DIGITAL_INPUT         (DALHAL_REACTIVE_FEATURE_READ) /* implemented */
// General Outputs
#define DALHAL_REACTIVE_CFG_DIGITAL_OUTPUT        (DALHAL_REACTIVE_FEATURE_VALUE_CHANGE | DALHAL_REACTIVE_FEATURE_WRITE) /* implemented */
//#define DALHAL_REACTIVE_CFG_PWM_ANALOG_WRITE      (DALHAL_REACTIVE_FEATURE_WRITE) OBSOLETE TO BE REMOVED
#define DALHAL_REACTIVE_CFG_SINGLE_PULSE_OUTPUT   (DALHAL_REACTIVE_FEATURE_VALUE_CHANGE | DALHAL_REACTIVE_FEATURE_WRITE | DALHAL_REACTIVE_FEATURE_EXEC) /* implemented */
// HomeAssistant
#define DALHAL_REACTIVE_CFG_HOMEASSISTANT         (DALHAL_REACTIVE_FEATURE_NONE) /* nothing to implement, only as a consumer */
// I2C
#define DALHAL_REACTIVE_CFG_I2C_MASTER            (DALHAL_REACTIVE_FEATURE_WRITE) /* implemented */
#define DALHAL_REACTIVE_CFG_I2C_DEVICE_PCF8574X   (DALHAL_REACTIVE_FEATURE_WRITE | DALHAL_REACTIVE_FEATURE_CUSTOM) /* implemented */
#define DALHAL_REACTIVE_CFG_I2C_DEVICE_MCP23017   (DALHAL_REACTIVE_FEATURE_WRITE | DALHAL_REACTIVE_FEATURE_CUSTOM)
// Lights
#define DALHAL_REACTIVE_CFG_WS2812                (DALHAL_REACTIVE_FEATURE_WRITE) /* implemented */
// REGO600
#define DALHAL_REACTIVE_CFG_REGO600               (DALHAL_REACTIVE_FEATURE_CYCLE_COMPLETE | DALHAL_REACTIVE_FEATURE_RW) /* implemented */
#define DALHAL_REACTIVE_CFG_REGO600_REGISTRY_ITEM (DALHAL_REACTIVE_FEATURE_VALUE_CHANGE) /* implemented */
// RF433
#define DALHAL_REACTIVE_CFG_TX433                 (DALHAL_REACTIVE_FEATURE_WRITE) /* implemented */
#define DALHAL_REACTIVE_CFG_TX433_UNIT            (DALHAL_REACTIVE_FEATURE_WRITE) /* implemented */
// Script
#define DALHAL_REACTIVE_CFG_SCRIPT_VARIABLE         (DALHAL_REACTIVE_FEATURE_VALUE_CHANGE) /* implemented */
#define DALHAL_REACTIVE_CFG_SCRIPT_CONSTVAR         (DALHAL_REACTIVE_FEATURE_NONE) /* nothing to implement, cannot either as read events from value ref is hard to implement */
#define DALHAL_REACTIVE_CFG_SCRIPT_WRITEVAR         (DALHAL_REACTIVE_FEATURE_VALUE_CHANGE) /* implemented */
#define DALHAL_REACTIVE_CFG_SCRIPT_ARRAY            (DALHAL_REACTIVE_FEATURE_BRACKET_WRITE) /*DALHAL_REACTIVE_FEATURE_BRACKET_READ | */ /* implemented */
#define DALHAL_REACTIVE_CFG_SCRIPT_EVENT_DISPATCHER (DALHAL_REACTIVE_FEATURE_EXEC)
// Sensors
#define DALHAL_REACTIVE_CFG_DHT                   (DALHAL_REACTIVE_FEATURE_VALUE_CHANGE) /* implemented */
#define DALHAL_REACTIVE_CFG_ONE_WIRE_TEMP_GROUP   (DALHAL_REACTIVE_FEATURE_CYCLE_COMPLETE) /* implemented */
#define DALHAL_REACTIVE_CFG_ONE_WIRE_TEMP_BUS     (DALHAL_REACTIVE_FEATURE_CYCLE_COMPLETE) /* implemented */
#define DALHAL_REACTIVE_CFG_ONE_WIRE_TEMP_DEVICE  (DALHAL_REACTIVE_FEATURE_VALUE_CHANGE) /* implemented */
// Templates
#define DALHAL_REACTIVE_CFG__TEMPLATE_            (DALHAL_REACTIVE_FEATURE_ALL) /* implemented */

#else // DEVELOPMENT MODE ALL FEATURES ACTIVE

// Actuators
#define DALHAL_REACTIVE_CFG_ACTUATOR              (DALHAL_REACTIVE_FEATURE_ALL) /* implemented */
#define DALHAL_REACTIVE_CFG_RELAY_LATCHING        (DALHAL_REACTIVE_FEATURE_ALL) /* implemented */
#define DALHAL_REACTIVE_CFG_PWM_SERVO             (DALHAL_REACTIVE_FEATURE_ALL) /* implemented */
// API

// DataStorageServices
#define DALHAL_REACTIVE_CFG_THINGSPEAK            (DALHAL_REACTIVE_FEATURE_ALL) /* implemented, also as a consumer */
// DeviceContainer
#define DALHAL_REACTIVE_CFG_CONTAINER             (DALHAL_REACTIVE_FEATURE_ALL) /* nothing to implement */
// Display

// General Inputs
#define DALHAL_REACTIVE_CFG_ANALOG_INPUT          (DALHAL_REACTIVE_FEATURE_ALL) /* implemented */
#define DALHAL_REACTIVE_CFG_BUTTON_INPUT          (DALHAL_REACTIVE_FEATURE_ALL) /* implemented */
#define DALHAL_REACTIVE_CFG_DIGITAL_INPUT         (DALHAL_REACTIVE_FEATURE_ALL) /* implemented */
// General Outputs
#define DALHAL_REACTIVE_CFG_DIGITAL_OUTPUT        (DALHAL_REACTIVE_FEATURE_ALL) /* implemented */
//#define DALHAL_REACTIVE_CFG_PWM_ANALOG_WRITE      (DALHAL_REACTIVE_FEATURE_ALL) OBSOLETE TO BE REMOVED
#define DALHAL_REACTIVE_CFG_SINGLE_PULSE_OUTPUT   (DALHAL_REACTIVE_FEATURE_ALL) /* implemented */
// HomeAssistant
#define DALHAL_REACTIVE_CFG_HOMEASSISTANT         (DALHAL_REACTIVE_FEATURE_ALL) /* nothing to implement, only as a consumer */
// I2C
#define DALHAL_REACTIVE_CFG_I2C_MASTER            (DALHAL_REACTIVE_FEATURE_ALL) /* implemented */
#define DALHAL_REACTIVE_CFG_I2C_DEVICE_PCF8574X   (DALHAL_REACTIVE_FEATURE_ALL) /* implemented */
#define DALHAL_REACTIVE_CFG_I2C_DEVICE_MCP23017   (DALHAL_REACTIVE_FEATURE_ALL)
// Lights
#define DALHAL_REACTIVE_CFG_WS2812                (DALHAL_REACTIVE_FEATURE_ALL) /* implemented */
// REGO600
#define DALHAL_REACTIVE_CFG_REGO600               (DALHAL_REACTIVE_FEATURE_ALL) /* implemented */
#define DALHAL_REACTIVE_CFG_REGO600_REGISTRY_ITEM (DALHAL_REACTIVE_FEATURE_ALL) /* implemented */
// RF433
#define DALHAL_REACTIVE_CFG_TX433                 (DALHAL_REACTIVE_FEATURE_ALL) /* implemented */
#define DALHAL_REACTIVE_CFG_TX433_UNIT            (DALHAL_REACTIVE_FEATURE_ALL) /* implemented */
// Script
#define DALHAL_REACTIVE_CFG_SCRIPT_VARIABLE       (DALHAL_REACTIVE_FEATURE_ALL) /* implemented */
#define DALHAL_REACTIVE_CFG_SCRIPT_CONSTVAR       (DALHAL_REACTIVE_FEATURE_ALL) /* nothing to implement, cannot either as read events from value ref is hard to implement */
#define DALHAL_REACTIVE_CFG_SCRIPT_WRITEVAR       (DALHAL_REACTIVE_FEATURE_ALL) /* implemented */
#define DALHAL_REACTIVE_CFG_SCRIPT_ARRAY          (DALHAL_REACTIVE_FEATURE_ALL) /* implemented */
#define DALHAL_REACTIVE_CFG_SCRIPT_EVENT_DISPATCHER (DALHAL_REACTIVE_FEATURE_ALL)
// Sensors
#define DALHAL_REACTIVE_CFG_DHT                   (DALHAL_REACTIVE_FEATURE_ALL) /* implemented */
#define DALHAL_REACTIVE_CFG_ONE_WIRE_TEMP_GROUP   (DALHAL_REACTIVE_FEATURE_ALL) /* implemented */
#define DALHAL_REACTIVE_CFG_ONE_WIRE_TEMP_BUS     (DALHAL_REACTIVE_FEATURE_ALL) /* implemented */
#define DALHAL_REACTIVE_CFG_ONE_WIRE_TEMP_DEVICE  (DALHAL_REACTIVE_FEATURE_ALL) /* implemented */
// Templates
#define DALHAL_REACTIVE_CFG__TEMPLATE_            (DALHAL_REACTIVE_FEATURE_ALL) /* implemented */


#endif

#define HAS_REACTIVE(name, feature) (DALHAL_REACTIVE_CFG_##name & DALHAL_REACTIVE_FEATURE_##feature)
#define USING_REACTIVE(name) (DALHAL_REACTIVE_CFG_##name)

#define DALHAL_DECLARE_REACTIVE_TABLE(CLASS_NAME) static const EventDescriptor ReactiveEventTable[];
#define DALHAL_DEFINE_REACTIVE_TABLE(CLASS_NAME)  const EventDescriptor CLASS_NAME::ReactiveEventTable[]

#define DALHAL_REACTIVE_EVENT_TABLENAME ReactiveEventTable

#define DALHAL_DEFINE_GET_REACTIVE_EVENT_FUNC(CLASS_NAME) \
    HALOperationResult CLASS_NAME::Get_ReactiveEvent(ZeroCopyString& zcFuncName, ReactiveEvent** reactiveEventOut) { \
        return Reactive::GetSimpleReactiveEventImpl(this, zcFuncName, reactiveEventOut, CLASS_NAME::ReactiveEventTable); \
    }

#define DALHAL_REACTIVE_EVENT_TABLE(name) \
    ((DALHAL_REACTIVE_CFG_##name) ? (ReactiveEventTable) : nullptr)

#define DALHAL_REACTIVE_ENTRY(CLASS_NAME, FEATURE_VAR_NAME) {#FEATURE_VAR_NAME, &CLASS_NAME::reactiveEventGetCounterPtr##FEATURE_VAR_NAME}


#define DALHAL_DECLARE_REACTIVE_FEATURE(CLASS_NAME, FEATURE_NAME) \
public: \
    uint32_t reactiveEventCounter##FEATURE_NAME = 0; \
    inline void trigger##FEATURE_NAME() { reactiveEventCounter##FEATURE_NAME++; } \
    inline static uint32_t* reactiveEventGetCounterPtr##FEATURE_NAME(Device* device) { return &(static_cast<CLASS_NAME*>(device)->reactiveEventCounter##FEATURE_NAME); }

#define HAS_REACTIVE_CUSTOM(name)                (DALHAL_REACTIVE_CFG_##name & DALHAL_REACTIVE_FEATURE_CUSTOM)
#define HAS_REACTIVE_BEGIN(name)                 (DALHAL_REACTIVE_CFG_##name & DALHAL_REACTIVE_FEATURE_BEGIN)
#define HAS_REACTIVE_CYCLE_COMPLETE(name)        (DALHAL_REACTIVE_CFG_##name & DALHAL_REACTIVE_FEATURE_CYCLE_COMPLETE)
#define HAS_REACTIVE_VALUE_CHANGE(name)          (DALHAL_REACTIVE_CFG_##name & DALHAL_REACTIVE_FEATURE_VALUE_CHANGE)
#define HAS_REACTIVE_STATE_CHANGE(name)          (DALHAL_REACTIVE_CFG_##name & DALHAL_REACTIVE_FEATURE_STATE_CHANGE)
#define HAS_REACTIVE_WRITE(name)                 (DALHAL_REACTIVE_CFG_##name & DALHAL_REACTIVE_FEATURE_WRITE)
#define HAS_REACTIVE_READ(name)                  (DALHAL_REACTIVE_CFG_##name & DALHAL_REACTIVE_FEATURE_READ)
#define HAS_REACTIVE_EXEC(name)                  (DALHAL_REACTIVE_CFG_##name & DALHAL_REACTIVE_FEATURE_EXEC)
#define HAS_REACTIVE_BRACKET_READ(name)          (DALHAL_REACTIVE_CFG_##name & DALHAL_REACTIVE_FEATURE_BRACKET_READ)
#define HAS_REACTIVE_BRACKET_WRITE(name)         (DALHAL_REACTIVE_CFG_##name & DALHAL_REACTIVE_FEATURE_BRACKET_WRITE)
#define HAS_REACTIVE_TIMEOUT(name)               (DALHAL_REACTIVE_CFG_##name & DALHAL_REACTIVE_FEATURE_TIMEOUT)
#define HAS_REACTIVE_READ_ERROR(name)            (DALHAL_REACTIVE_CFG_##name & DALHAL_REACTIVE_FEATURE_READ_ERROR)
#define HAS_REACTIVE_WRITE_ERROR(name)           (DALHAL_REACTIVE_CFG_##name & DALHAL_REACTIVE_FEATURE_WRITE_ERROR)
#define HAS_REACTIVE_EXEC_ERROR(name)            (DALHAL_REACTIVE_CFG_##name & DALHAL_REACTIVE_FEATURE_EXEC_ERROR)

#define REACTIVE_ENTRY_BEGIN(CLASS_NAME)          DALHAL_REACTIVE_ENTRY(CLASS_NAME, Begin)
#define REACTIVE_ENTRY_CYCLE_COMPLETE(CLASS_NAME) DALHAL_REACTIVE_ENTRY(CLASS_NAME, CycleComplete)
#define REACTIVE_ENTRY_VALUE_CHANGE(CLASS_NAME)   DALHAL_REACTIVE_ENTRY(CLASS_NAME, ValueChange)
#define REACTIVE_ENTRY_STATE_CHANGE(CLASS_NAME)   DALHAL_REACTIVE_ENTRY(CLASS_NAME, StateChange)
#define REACTIVE_ENTRY_WRITE(CLASS_NAME)          DALHAL_REACTIVE_ENTRY(CLASS_NAME, Write)
#define REACTIVE_ENTRY_READ(CLASS_NAME)           DALHAL_REACTIVE_ENTRY(CLASS_NAME, Read)
#define REACTIVE_ENTRY_EXEC(CLASS_NAME)           DALHAL_REACTIVE_ENTRY(CLASS_NAME, Exec)
#define REACTIVE_ENTRY_BRACKET_READ(CLASS_NAME)   DALHAL_REACTIVE_ENTRY(CLASS_NAME, BracketRead)
#define REACTIVE_ENTRY_BRACKET_WRITE(CLASS_NAME)  DALHAL_REACTIVE_ENTRY(CLASS_NAME, BracketWrite)
#define REACTIVE_ENTRY_TIMEOUT(CLASS_NAME)        DALHAL_REACTIVE_ENTRY(CLASS_NAME, Timeout)
#define REACTIVE_ENTRY_READ_ERROR(CLASS_NAME)     DALHAL_REACTIVE_ENTRY(CLASS_NAME, ReadError)
#define REACTIVE_ENTRY_WRITE_ERROR(CLASS_NAME)    DALHAL_REACTIVE_ENTRY(CLASS_NAME, WriteError)
#define REACTIVE_ENTRY_EXEC_ERROR(CLASS_NAME)     DALHAL_REACTIVE_ENTRY(CLASS_NAME, ExecError)


// Terminator for all tables
#define REACTIVE_ENTRY__TERMINATOR_()             { nullptr, nullptr }

#define REACTIVE_ENTRY_BEGIN_TEST(NAME, CLASS_NAME)    HAS_REACTIVE_BEGIN(NAME) ? DALHAL_REACTIVE_ENTRY(CLASS_NAME, Begin) : REACTIVE_ENTRY__TERMINATOR_()


#define REACTIVE_DECLARE_FEATURE_BEGIN(CLASS_NAME)          DALHAL_DECLARE_REACTIVE_FEATURE(CLASS_NAME, Begin)
#define REACTIVE_DECLARE_CYCLE_COMPLETE(CLASS_NAME)         DALHAL_DECLARE_REACTIVE_FEATURE(CLASS_NAME, CycleComplete)
#define REACTIVE_DECLARE_FEATURE_VALUE_CHANGE(CLASS_NAME)   DALHAL_DECLARE_REACTIVE_FEATURE(CLASS_NAME, ValueChange)
#define REACTIVE_DECLARE_FEATURE_STATE_CHANGE(CLASS_NAME)   DALHAL_DECLARE_REACTIVE_FEATURE(CLASS_NAME, StateChange)
#define REACTIVE_DECLARE_FEATURE_WRITE(CLASS_NAME)          DALHAL_DECLARE_REACTIVE_FEATURE(CLASS_NAME, Write)
#define REACTIVE_DECLARE_FEATURE_READ(CLASS_NAME)           DALHAL_DECLARE_REACTIVE_FEATURE(CLASS_NAME, Read)
#define REACTIVE_DECLARE_FEATURE_EXEC(CLASS_NAME)           DALHAL_DECLARE_REACTIVE_FEATURE(CLASS_NAME, Exec)
#define REACTIVE_DECLARE_FEATURE_BRACKET_READ(CLASS_NAME)   DALHAL_DECLARE_REACTIVE_FEATURE(CLASS_NAME, BracketRead)
#define REACTIVE_DECLARE_FEATURE_BRACKET_WRITE(CLASS_NAME)  DALHAL_DECLARE_REACTIVE_FEATURE(CLASS_NAME, BracketWrite)
#define REACTIVE_DECLARE_FEATURE_TIMEOUT(CLASS_NAME)        DALHAL_DECLARE_REACTIVE_FEATURE(CLASS_NAME, Timeout)
#define REACTIVE_DECLARE_FEATURE_READ_ERROR(CLASS_NAME)     DALHAL_DECLARE_REACTIVE_FEATURE(CLASS_NAME, ReadError)
#define REACTIVE_DECLARE_FEATURE_WRITE_ERROR(CLASS_NAME)    DALHAL_DECLARE_REACTIVE_FEATURE(CLASS_NAME, WriteError)
#define REACTIVE_DECLARE_FEATURE_EXEC_ERROR(CLASS_NAME)     DALHAL_DECLARE_REACTIVE_FEATURE(CLASS_NAME, ExecError)

template<typename T>
static void GenericValueCallback(void* ctx) {
    static_cast<T*>(ctx)->triggerValueChange();
}